language: java
install: true

jdk:
  - openjdk11

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x gradlew


before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html

script:
  - ./gradlew :spring-boot-project:spring-boot-docs-zh:asciidoctor


deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: us-east-2
  bucket: "com.edtestbank.docs"
  skip_cleanup: true
  local_dir: spring-boot-docs-zh/build
  upload-dir: spring-boot-docs
