[[boot-documentation]]
= Spring Boot 文档（Documentation）
include::attributes.adoc[]

本部分提供了有关 Spring Boot 参考文档的概述。同时为余下的文档内容提供了一个类似地图的导航和概述。



[[boot-documentation-about]]
== 关于这个文档
Spring Boot 参考指南提供下面的几种可用版本：

* {spring-boot-docs}/html/[多页 HTML 格式]
* {spring-boot-docs}/htmlsingle/[单页 HTML 格式]
* {spring-boot-docs}/pdf/spring-boot-reference.pdf[PDF]

最新的版本拷贝可以在  {spring-boot-current-docs} 中查看。

拷贝本文档可以供你自己进行修改或者对修改后进行发布给其他用户，不管是电子版本还是纸介质版本都是可以的。
但你不能对你的拷贝版本进行收费，同时还需要在你的版本中包含有版权信息。


[[boot-documentation-getting-help]]
== 获得帮助
如果你在使用 Spring Boot 的时候遇到问题，并且希望能够获得一些帮助，你可以：

* 访问  <<howto.adoc#howto, 如何使用文档>>。
  在如何使用文档中提供了针对一些最常见问题的解决方案。
* 学习 Spring 有关的基础知识。
  Spring Boot 被用来构建很多 Spring 的项目，请访问 https://spring.io[spring.io] 网站。该网站中提供了很多有用的参考文件。
  如果你尝试开始使用 Spring，请访问  https://spring.io/guides[guides] 页面中的内容。
* 询问一个问题
  Spring 的官方小组将会一直关注 https://stackoverflow.com[stackoverflow.com] 网站中被标记为 https://stackoverflow.com/tags/spring-boot[`spring-boot`] 的问题。
* 反馈有关 Spring Boot 的 Bug 和错误，请访问 https://github.com/spring-projects/spring-boot/issues。

NOTE: 所有 Spring Boot 的项目和内容都是开源的，包括这个文档也是开源的，如果你在使用的时候发现了一些问题包括这个文档的问题，并且希望改善文档的话，请访问 {spring-boot-code}[加入项目组] 页面。



[[boot-documentation-upgrading]]
== 从早期版本进行升级
如何从早期的 Spring Boot 版本进行升级的内容被放置在 {github-wiki}[wiki] 页面中。
请访问 {github-wiki}#release-notes[release notes] 部分的内容来找到你希望进行升级的版本。

有关升级的指南总是会放在发行日志的最前面。
如果你不是按照主要版本进行升级的，你的升级版本已经落后了不少版本的话，请阅读你将要跳过的升级版本的日志。

你应该确保你的 Spring Boot 总是能够在 {github-wiki}/Supported-Versions[支持的版本] 下运行。



[[boot-documentation-first-steps]]
== 第一步
If you are getting started with Spring Boot or 'Spring' in general, start with <<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:* <<getting-started.adoc#getting-started-introducing-spring-boot, Overview>> | <<getting-started.adoc#getting-started-system-requirements, Requirements>> | <<getting-started.adoc#getting-started-installing-spring-boot, Installation>>
* *Tutorial:* <<getting-started.adoc#getting-started-first-application, Part 1>> | <<getting-started.adoc#getting-started-first-application-code, Part 2>>
* *Running your example:* <<getting-started.adoc#getting-started-first-application-run, Part 1>> | <<getting-started.adoc#getting-started-first-application-executable-jar, Part 2>>



== Working with Spring Boot
Ready to actually start using Spring Boot? <<using-spring-boot.adoc#using-boot, We have you covered>>:

* *Build systems:* <<using-spring-boot.adoc#using-boot-maven, Maven>> | <<using-spring-boot.adoc#using-boot-gradle, Gradle>> | <<using-spring-boot.adoc#using-boot-ant, Ant>> | <<using-spring-boot.adoc#using-boot-starter, Starters>>
* *Best practices:* <<using-spring-boot.adoc#using-boot-structuring-your-code, Code Structure>> | <<using-spring-boot.adoc#using-boot-configuration-classes, @Configuration>> | <<using-spring-boot.adoc#using-boot-auto-configuration, @EnableAutoConfiguration>> | <<using-spring-boot.adoc#using-boot-spring-beans-and-dependency-injection, Beans and Dependency Injection>>
* *Running your code:* <<using-spring-boot.adoc#using-boot-running-from-an-ide, IDE>> | <<using-spring-boot.adoc#using-boot-running-as-a-packaged-application, Packaged>> | <<using-spring-boot.adoc#using-boot-running-with-the-maven-plugin, Maven>> | <<using-spring-boot.adoc#using-boot-running-with-the-gradle-plugin, Gradle>>
* *Packaging your app:* <<using-spring-boot.adoc#using-boot-packaging-for-production, Production jars>>
* *Spring Boot CLI:* <<spring-boot-cli.adoc#cli, Using the CLI>>



== Learning about Spring Boot Features
Need more details about Spring Boot's core features?
<<spring-boot-features.adoc#boot-features, The following content is for you>>:

* *Core Features:* <<spring-boot-features.adoc#boot-features-spring-application, SpringApplication>> | <<spring-boot-features.adoc#boot-features-external-config, External Configuration>> | <<spring-boot-features.adoc#boot-features-profiles, Profiles>> | <<spring-boot-features.adoc#boot-features-logging, Logging>>
* *Web Applications:* <<spring-boot-features.adoc#boot-features-spring-mvc, MVC>> | <<spring-boot-features.adoc#boot-features-embedded-container, Embedded Containers>>
* *Working with data:* <<spring-boot-features.adoc#boot-features-sql, SQL>> | <<spring-boot-features.adoc#boot-features-nosql, NO-SQL>>
* *Messaging:* <<spring-boot-features.adoc#boot-features-messaging, Overview>> | <<spring-boot-features.adoc#boot-features-jms, JMS>>
* *Testing:* <<spring-boot-features.adoc#boot-features-testing, Overview>> | <<spring-boot-features.adoc#boot-features-testing-spring-boot-applications, Boot Applications>> | <<spring-boot-features.adoc#boot-features-test-utilities, Utils>>
* *Extending:* <<spring-boot-features.adoc#boot-features-developing-auto-configuration, Auto-configuration>> | <<spring-boot-features.adoc#boot-features-condition-annotations, @Conditions>>



== Moving to Production
When you are ready to push your Spring Boot application to production, we have <<production-ready-features.adoc#production-ready, some tricks>> that you might like:

* *Management endpoints:* <<production-ready-features.adoc#production-ready-endpoints, Overview>>
* *Connection options:* <<production-ready-features.adoc#production-ready-monitoring, HTTP>> | <<production-ready-features.adoc#production-ready-jmx, JMX>>
* *Monitoring:* <<production-ready-features.adoc#production-ready-metrics, Metrics>> | <<production-ready-features.adoc#production-ready-auditing, Auditing>> | <<production-ready-features.adoc#production-ready-http-tracing, HTTP Tracing>> | <<production-ready-features.adoc#production-ready-process-monitoring, Process>>



== Advanced Topics
Finally, we have a few topics for more advanced users:

* *Spring Boot Applications Deployment:* <<deployment.adoc#cloud-deployment, Cloud Deployment>> | <<deployment.adoc#deployment-service, OS Service>>
* *Build tool plugins:* <<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven>> | <<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle>>
* *Appendix:* <<appendix-application-properties.adoc#common-application-properties,Application Properties>> | <<appendix-configuration-metadata.adoc#configuration-metadata,Configuration Metadata>> | <<appendix-auto-configuration-classes.adoc#auto-configuration-classes,Auto-configuration Classes>> | <<appendix-test-auto-configuration.adoc#test-auto-configuration,Test Auto-configuration Annotations>> | <<appendix-executable-jar-format.adoc#executable-jar,Executable Jars>> | <<appendix-dependency-versions.adoc#dependency-versions,Dependency Versions>>
