[[getting-started]]
= 开始使用
include::attributes.adoc[]

如果你现在正在开始使用 Spring Boot，或者有关 "`Spring`" 的相关内容，建议你开始阅读本中有关的内容。
这个通常能够回答你有关一些的基本知识，包括有"`什么是（what?）`", "`如何开始（how?）`" and "`为什么（why?）`" 等有关的问题。
这个部分包括有对 Spring Boot 的介绍，以及包括有安装的指南。
我们将会和你一起构建你的第一个 Spring Boot 应用程序，然后讨论一些我们需要了解的核心概念。



[[getting-started-introducing-spring-boot]]
== Spring Boot 介绍
Spring Boot 能够帮助你创建独立运行（stand-alone），基于 Spring 可在生产环境（production-grade）中运行的应用。
在 Spring 官方的文档中对 Spring 平台和使用的一些第三方类库进行了一些说明描述，因此你可以使用这些只是能够在很短的时间内开始使用 Spring Boot。
绝大部分的 Spring Boot 应用只需要一些很少的 Spring 配置就可以运行了。

你可以使用 Spring Boot 来创建一个 Java 应用程序，这个 Java 应用程序可以使用 `java -jar` 来运行，同时也可以使用传统的 Web 部署（war deployments）。
我们同时也提供了一个命令行工具来运行 "`spring scripts`"。

我们主要的目的是：

* 针对所有的 Spring 开发提供了一个广泛的快速和开始使用经验。
* 因为开始默认需求和实际的开发有所出入，我们提供了开箱即用的能够，能够让你更快的适应你的业务。
* 针对很多项目都需要的通用要求，我们也提供了一个广泛的非功能性特性（例如，嵌入式服务，安全性，矩阵，系统健康检查和外部扩展功能）。
* 你完全可以不需要使用代码生成功能，也不需要对 XML 进行配置。



[[getting-started-system-requirements]]
== 系统要求
Spring Boot {spring-boot-version} 版本要求至少 https://www.java.com[Java 8] 及其以上版本，目前最高能够支持到 Java 15 （包含 15）的版本。
{spring-framework-docs}/[Spring 框架（Framework） {spring-framework-version}] 的版本或者以上的版本是必须的。

能够被下面的编译工具支持：

|===
| 编译工具 | 版本

| Maven
| 3.3+

| Gradle
| 6 (6.3 或者后续版本)。 5.6.x 也是能够被支持的，但是已经准备开始不被兼容了。
|===



[[getting-started-system-requirements-servlet-containers]]
=== Servlet 容器
Spring Boot 能够支持下面的嵌入 Servlet 容器版本：

|===
| 名字 | Servlet 版本

| Tomcat 9.0
| 4.0

| Jetty 9.4
| 3.1

| Undertow 2.0
| 4.0
|===

当然，你也可以将 Spring Boot 应用部署到任何能够兼容 3.1+ 容器版本的服务器上。



[[getting-started-installing-spring-boot]]
== 安装 Spring Boot
Spring Boot 可以通过使用 "`传统（classic）`" 的 Java 开发工具或者安装一个命令行工具（command line tool）。
不管通过何种方式进行安装，你都需要  https://www.java.com[Java SDK v1.8] 或者更高的版本。
在进行安装之前，你需要通过下面的命令来检查你的环境中是否已经有安装正确的 JDK 版本。

[indent=0]
----
	$ java -version
----

如果你是一个 Java 开发的初学者或者希望对 Spring Boot 有所了解，你可能希望尝试下官方提供的  <<getting-started-installing-the-cli, Spring Boot CLI>> (命令行工具 Command Line Interface) 。
否则的话，你可以尝试从 "`传统（classic）`" 的安装介绍中开始。



[[getting-started-installation-instructions-for-java]]
=== 针对 Java 开发者的安装指南
你可以与任何 Java 标准库相同的方式来使用 Spring Boot。
为了能够让你的项目使用 Spring Boot ，将 `+spring-boot-*.jar+` 文件放到你项目中正确的 classpath 中。
Spring Boot 是不需要任何特殊的工具来进行整合的，所以你可以方便的使用任何 IDE 或者 文本编辑器。
另外的，针对 Spring Boot 应用程序也没有任何特殊的地方，你可以和你以往对 Java 进行开发的流程一样对 Spring Boot 应用进行调试（debug）。

尽管，你 _可以使用_ 拷贝 Spring Boot 的 Jar 包到你的项目路径中来运行项目，我们还是非常建议你使用一些构建工具来对依赖进行管理（例如 Maven 或者 Gradle）。



[[getting-started-maven-installation]]
==== Maven 安装
Spring Boot 能够与 Apache Maven 3.3 及其以上的版本进行兼容。
如果你的计算机或者环境中还没有安装 Maven ，请参考 https://maven.apache.org 页面中的内容来对 Maven 进行安装。

TIP: 在很多操作系统中，Maven 是可以通过一个包管理工具来进行安装的。
如果你使用的是 OSX Homebrew 操作系统，尝试运行 `brew install maven` 来进行安装。
Ubuntu 的用户可以通过运行 `sudo apt-get install maven` 来进行安装
Windows 用户也可以使用 https://chocolatey.org/[Chocolatey] 来进行安装，你需要运行 `choco install maven` 命令（这个命令运行需要具有管理员权限）。

Spring Boot 的依赖使用 `org.springframework.boot` `groupId` 来声明。
通常来说，你的 Maven POM 文件需要继承 `spring-boot-starter-parent` 项目，同时还需要声明一个或者多个 <<using-spring-boot.adoc#using-boot-starter,"`Starters`">>。
Spring Boot 同时也提供了一个可选项的 <<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven 插件（plugin）>> 来被用来创建可执行的 Jars。

更多有关开始使用 Spring Boot 和 Maven 的相关文章和内容可以在页面 {spring-boot-maven-plugin-docs}#getting-started[开始使用部分] 中找到。同时有关 Maven 插件的参考页可以在这里找到。



[[getting-started-gradle-installation]]
==== Gradle 安装
Spring Boot 能够兼容 Gradle 6 （6.3 或者后续版本）。
Gradle 5.6.x 也是能够被支持的，但是这个支持将会在后续的发布中删除。
如果你的计算机中还没有安装 Gradle ，请参考页面 https://gradle.org 中的内容来安装 Gradle。

Spring Boot 的依赖使用 `org.springframework.boot` `group` 来声明。
通常来说，你的项目需要声明一个或者多个  <<using-spring-boot.adoc#using-boot-starter, "`Starters`">>。
Spring Boot 同时也提供了一个 <<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle 插件（plugin）>> ，这个插件能够对依赖声明进行简化，同时被用来创建一个可执行的 Jars。

.Gradle Wrapper
****
Gradle Wrapper 能够为你在构建一个项目的时候，提供了一个非常简单的方式来  "`获得`" Gradle。
Gradle Wrapper 是一个小的脚本和库，你可以通过这个脚本和库来启动构建进程，通常并不需要安装 Gradle。
请查看 {gradle-docs}/gradle_wrapper.html 页面来获得更多的细节。
****

更多有关开始使用 Spring Boot 和 Gradle 的相关文章和内容可以在页面 {spring-boot-gradle-plugin-docs}#getting-started[开始使用部分] 中找到。同时有关 Gradle 插件的参考页可以在这里找到。



[[getting-started-installing-the-cli]]
=== 安装 Spring Boot 命令行
Spring Boot CLI (Command Line Interface) 是一个你可以用来快速初始化 Spring 的命令行工具。
Spring Boot 的命令行工具能够让你运行 https://groovy-lang.org/[Groovy] 脚本。这个脚本有着类似 Java 的句法。

在运行和构建 Spring Boot 应用的时候，CLI 这个工具并不是必须需要安装的。哪怕你不安装 CLI，你也能够非常快速的运行 Spring Boot 应用，但是这个官方提供的小工具能够让你更快的使用 Spring Boot。



[[getting-started-manual-cli-installation]]
==== 手工安装
你可以从 Spring 的软件仓库中下载 Spring CLI 后进行安装。

可用的下载地址，请参考下面的链接：

* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.zip[spring-boot-cli-{spring-boot-version}-bin.zip]
* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.tar.gz[spring-boot-cli-{spring-boot-version}-bin.tar.gz]

Sapshot 版本下载，snapshot 版本的意思是从最新的源代码库中进行编译构建的，通常这个版本具有更多的 Bug 修复，下载地址请访问下面的链接：
https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-cli/[snapshot 构建版本]

当你完成需要的归档文件下载到你本地计算机后，请按照链接： {github-raw}/spring-boot-project/spring-boot-cli/src/main/content/INSTALL.txt[INSTALL.txt] 安装指南的内容来解压。
整体来说，Spring CLI 是一个 `spring` 脚本 (针对 Windows 使用的是`spring.bat` )。这个可以运行的脚本文件能够在你对 `.zip` 文件解压的 `bin/` 文件夹中找到。
你还可以使用另外一个办法来使用 Spring CLI：通过一个 `.jar` 的文件使用 `java -jar` 来进行运行（在运行这个 jar 的时候，你需要确定这个 Jar 文件已经放置到了你系统中的 classpath 路径中）。



[[getting-started-sdkman-cli-installation]]
==== 使用 SDKMAN! 安装
针对在变量中设置多个版本的 SDK，你可以使用 SDKMAN! (The Software Development Kit Manager) 来进行安装。
Groovy 和 Spring Boot CLI 都已经部署到 SDKMAN! 中了，在你本地计算机中配置好 SDKMAN! 环境后，你就可以使用多版本的 Groovy 和 Spring Boot CLI。
可以使用下面的命令来通过 https://sdkman.io 来安装 Spring Boot：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk install springboot
	$ spring --version
	Spring Boot v{spring-boot-version}
----

如果你正在针对 CLI 的一些特性进行开发的话，并且你希望使用你本地编译的 CLI 构建版本安装到 SDKMAN! 中的话，你可以通过运行下面的命令来进行版本的切换：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-{spring-boot-version}-bin/spring-{spring-boot-version}/
	$ sdk default springboot dev
	$ spring --version
	Spring CLI v{spring-boot-version}
----

上面的命令显示了一个被命名为 `dev` 的 `spring` 实例安装的安装命令和安装校验。同时路径（Path）还指向到了构建的位置，因此每次通过代码重构后，你都会使用最新的 `spring` 版本。

如果你需要检查安装的版本和相关的配置，请运行下面的命令：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk ls springboot

	================================================================================
	Available Springboot Versions
	================================================================================
	> + dev
	* {spring-boot-version}

	================================================================================
	+ - local version
	* - installed
	> - currently in use
	================================================================================
----



[[getting-started-homebrew-cli-installation]]
==== OSX Homebrew 安装
如果你是 Mac 的用户，并且在你的 Mac 计算机上已经安装了 https://brew.sh/[Homebrew] 应用的话，你可以通过使用下面的命令行工具来安装 Spring Boot CLI：

[indent=0]
----
	$ brew tap pivotal/tap
	$ brew install springboot
----

Homebrew 将会把 `spring` 安装到 `/usr/local/bin` 目录下。

NOTE: 如果你在安装的过程中出现了一些异常，或者显示包没有找到，或者没有办法进行安装，那么很有可能是安装的 brew 版本过老，需要进行更新了。If you do not see the formula, your installation of brew might be out-of-date.
你可以直接运行 `brew update` 命令先进行更新，然后再次尝试进行安装。



[[getting-started-macports-cli-installation]]
==== MacPorts 安装
If you are on a Mac and use https://www.macports.org/[MacPorts], you can install the Spring Boot CLI by using the following command:

[indent=0]
----
	$ sudo port install spring-boot-cli
----



[[getting-started-cli-command-line-completion]]
==== Command-line 完成
The Spring Boot CLI includes scripts that provide command completion for the https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29[BASH] and https://en.wikipedia.org/wiki/Z_shell[zsh] shells.
You can `source` the script (also named `spring`) in any shell or put it in your personal or system-wide bash completion initialization.
On a Debian system, the system-wide scripts are in `/shell-completion/bash` and all scripts in that directory are executed when a new shell starts.
For example, to run the script manually if you have installed by using SDKMAN!, use the following commands:

[indent=0]
----
	$ . ~/.sdkman/candidates/springboot/current/shell-completion/bash/spring
	$ spring <HIT TAB HERE>
	  grab  help  jar  run  test  version
----

NOTE: If you install the Spring Boot CLI by using Homebrew or MacPorts, the command-line completion scripts are automatically registered with your shell.



[[getting-started-scoop-cli-installation]]
==== Windows Scoop 安装
If you are on a Windows and use https://scoop.sh/[Scoop], you can install the Spring Boot CLI by using the following commands:

[indent=0]
----
	> scoop bucket add extras
	> scoop install springboot
----

Scoop installs `spring` to `~/scoop/apps/springboot/current/bin`.

NOTE: If you do not see the app manifest, your installation of scoop might be out-of-date.
In that case, run `scoop update` and try again.



[[getting-started-cli-example]]
==== Spring CLI 快速使用示例
You can use the following web application to test your installation.
To start, create a file called `app.groovy`, as follows:

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
	@RestController
	class ThisWillActuallyRun {

		@RequestMapping("/")
		String home() {
			"Hello World!"
		}

	}
----

Then run it from a shell, as follows:

[indent=0]
----
	$ spring run app.groovy
----

NOTE: The first run of your application is slow, as dependencies are downloaded.
Subsequent runs are much quicker.

Open `http://localhost:8080` in your favorite web browser.
You should see the following output:

[indent=0]
----
	Hello World!
----



[[getting-started-upgrading-from-an-earlier-version]]
=== Upgrading from an Earlier Version of Spring Boot
If you are upgrading from the `1.x` release of Spring Boot, check the {github-wiki}/Spring-Boot-2.0-Migration-Guide["`migration guide`" on the project wiki] that provides detailed upgrade instructions.
Check also the {github-wiki}["`release notes`"] for a list of "`new and noteworthy`" features for each release.

When upgrading to a new feature release, some properties may have been renamed or removed.
Spring Boot provides a way to analyze your application's environment and print diagnostics at startup, but also temporarily migrate properties at runtime for you.
To enable that feature, add the following dependency to your project:

[source,xml,indent=0]
----
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-properties-migrator</artifactId>
		<scope>runtime</scope>
	</dependency>
----

WARNING: Properties that are added late to the environment, such as when using `@PropertySource`, will not be taken into account.

NOTE: Once you're done with the migration, please make sure to remove this module from your project's dependencies.

To upgrade an existing CLI installation, use the appropriate package manager command (for example, `brew upgrade`).
If you manually installed the CLI, follow the <<getting-started-manual-cli-installation, standard instructions>>, remembering to update your `PATH` environment variable to remove any older references.



[[getting-started-first-application]]
== Developing Your First Spring Boot Application
This section describes how to develop a small "`Hello World!`" web application that highlights some of Spring Boot's key features.
We use Maven to build this project, since most IDEs support it.

[TIP]
====
The https://spring.io[spring.io] web site contains many "`Getting Started`" https://spring.io/guides[guides] that use Spring Boot.
If you need to solve a specific problem, check there first.

You can shortcut the steps below by going to https://start.spring.io and choosing the "Web" starter from the dependencies searcher.
Doing so generates a new project structure so that you can <<getting-started-first-application-code,start coding right away>>.
Check the {spring-initializr-docs}/#user-guide[Spring Initializr documentation] for more details.
====

Before we begin, open a terminal and run the following commands to ensure that you have valid versions of Java and Maven installed:

[indent=0]
----
	$ java -version
	java version "1.8.0_102"
	Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
	Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
----

[indent=0]
----
	$ mvn -v
	Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
	Maven home: /usr/local/Cellar/maven/3.3.9/libexec
	Java version: 1.8.0_102, vendor: Oracle Corporation
----

NOTE: This sample needs to be created in its own directory.
Subsequent instructions assume that you have created a suitable directory and that it is your current directory.



[[getting-started-first-application-pom]]
=== Creating the POM
We need to start by creating a Maven `pom.xml` file.
The `pom.xml` is the recipe that is used to build your project.
Open your favorite text editor and add the following:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
		<modelVersion>4.0.0</modelVersion>

		<groupId>com.example</groupId>
		<artifactId>myproject</artifactId>
		<version>0.0.1-SNAPSHOT</version>

		<parent>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-parent</artifactId>
			<version>{spring-boot-version}</version>
		</parent>

		<description/>
		<developers>
			<developer/>
		</developers>
		<licenses>
			<license/>
		</licenses>
		<scm>
			<url/>
		</scm>
		<url/>

		<!-- Additional lines to be added here... -->

ifeval::["{spring-boot-artifactory-repo}" != "release"]
		<!-- (you don't need this if you are using a .RELEASE version) -->
		<repositories>
			<repository>
				<id>spring-snapshots</id>
				<url>https://repo.spring.io/snapshot</url>
				<snapshots><enabled>true</enabled></snapshots>
			</repository>
			<repository>
				<id>spring-milestones</id>
				<url>https://repo.spring.io/milestone</url>
			</repository>
		</repositories>
		<pluginRepositories>
			<pluginRepository>
				<id>spring-snapshots</id>
				<url>https://repo.spring.io/snapshot</url>
			</pluginRepository>
			<pluginRepository>
				<id>spring-milestones</id>
				<url>https://repo.spring.io/milestone</url>
			</pluginRepository>
		</pluginRepositories>
endif::[]
	</project>
----

The preceding listing should give you a working build.
You can test it by running `mvn package` (for now, you can ignore the "`jar will be empty - no content was marked for inclusion!`" warning).

NOTE: At this point, you could import the project into an IDE (most modern Java IDEs include built-in support for Maven).
For simplicity, we continue to use a plain text editor for this example.



[[getting-started-first-application-dependencies]]
=== Adding Classpath Dependencies
Spring Boot provides a number of "`Starters`" that let you add jars to your classpath.
Our applications for smoke tests use the `spring-boot-starter-parent` in the `parent` section of the POM.
The `spring-boot-starter-parent` is a special starter that provides useful Maven defaults.
It also provides a <<using-spring-boot.adoc#using-boot-dependency-management,`dependency-management`>> section so that you can omit `version` tags for "`blessed`" dependencies.

Other "`Starters`" provide dependencies that you are likely to need when developing a specific type of application.
Since we are developing a web application, we add a `spring-boot-starter-web` dependency.
Before that, we can look at what we currently have by running the following command:

[indent=0]
----
	$ mvn dependency:tree

	[INFO] com.example:myproject:jar:0.0.1-SNAPSHOT
----

The `mvn dependency:tree` command prints a tree representation of your project dependencies.
You can see that `spring-boot-starter-parent` provides no dependencies by itself.
To add the necessary dependencies, edit your `pom.xml` and add the `spring-boot-starter-web` dependency immediately below the `parent` section:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>
----

If you run `mvn dependency:tree` again, you see that there are now a number of additional dependencies, including the Tomcat web server and Spring Boot itself.



[[getting-started-first-application-code]]
=== Writing the Code
To finish our application, we need to create a single Java file.
By default, Maven compiles sources from `src/main/java`, so you need to create that directory structure and then add a file named `src/main/java/Example.java` to contain the following code:

[source,java,indent=0]
----
	import org.springframework.boot.*;
	import org.springframework.boot.autoconfigure.*;
	import org.springframework.web.bind.annotation.*;

	@RestController
	@EnableAutoConfiguration
	public class Example {

		@RequestMapping("/")
		String home() {
			return "Hello World!";
		}

		public static void main(String[] args) {
			SpringApplication.run(Example.class, args);
		}

	}
----

Although there is not much code here, quite a lot is going on.
We step through the important parts in the next few sections.



[[getting-started-first-application-annotations]]
==== The @RestController and @RequestMapping Annotations
The first annotation on our `Example` class is `@RestController`.
This is known as a _stereotype_ annotation.
It provides hints for people reading the code and for Spring that the class plays a specific role.
In this case, our class is a web `@Controller`, so Spring considers it when handling incoming web requests.

The `@RequestMapping` annotation provides "`routing`" information.
It tells Spring that any HTTP request with the `/` path should be mapped to the `home` method.
The `@RestController` annotation tells Spring to render the resulting string directly back to the caller.

TIP: The `@RestController` and `@RequestMapping` annotations are Spring MVC annotations (they are not specific to Spring Boot).
See the {spring-framework-docs}/web.html#mvc[MVC section] in the Spring Reference Documentation for more details.



[[getting-started-first-application-auto-configuration]]
==== The @EnableAutoConfiguration Annotation
The second class-level annotation is `@EnableAutoConfiguration`.
This annotation tells Spring Boot to "`guess`" how you want to configure Spring, based on the jar dependencies that you have added.
Since `spring-boot-starter-web` added Tomcat and Spring MVC, the auto-configuration assumes that you are developing a web application and sets up Spring accordingly.

.Starters and Auto-configuration
****
Auto-configuration is designed to work well with "`Starters`", but the two concepts are not directly tied.
You are free to pick and choose jar dependencies outside of the starters.
Spring Boot still does its best to auto-configure your application.
****



[[getting-started-first-application-main-method]]
==== The "`main`" Method
The final part of our application is the `main` method.
This is a standard method that follows the Java convention for an application entry point.
Our main method delegates to Spring Boot's `SpringApplication` class by calling `run`.
`SpringApplication` bootstraps our application, starting Spring, which, in turn, starts the auto-configured Tomcat web server.
We need to pass `Example.class` as an argument to the `run` method to tell `SpringApplication` which is the primary Spring component.
The `args` array is also passed through to expose any command-line arguments.



[[getting-started-first-application-run]]
=== Running the Example
At this point, your application should work.
Since you used the `spring-boot-starter-parent` POM, you have a useful `run` goal that you can use to start the application.
Type `mvn spring-boot:run` from the root project directory to start the application.
You should see output similar to the following:

[indent=0,subs="attributes"]
----
	$ mvn spring-boot:run

	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::  (v{spring-boot-version})
	....... . . .
	....... . . . (log output here)
	....... . . .
	........ Started Example in 2.222 seconds (JVM running for 6.514)
----

If you open a web browser to `http://localhost:8080`, you should see the following output:

[indent=0]
----
	Hello World!
----

To gracefully exit the application, press `ctrl-c`.



[[getting-started-first-application-executable-jar]]
=== Creating an Executable Jar
We finish our example by creating a completely self-contained executable jar file that we could run in production.
Executable jars (sometimes called "`fat jars`") are archives containing your compiled classes along with all of the jar dependencies that your code needs to run.

.Executable jars and Java
****
Java does not provide a standard way to load nested jar files (jar files that are themselves contained within a jar).
This can be problematic if you are looking to distribute a self-contained application.

To solve this problem, many developers use "`uber`" jars.
An uber jar packages all the classes from all the application's dependencies into a single archive.
The problem with this approach is that it becomes hard to see which libraries are in your application.
It can also be problematic if the same filename is used (but with different content) in multiple jars.

Spring Boot takes a <<appendix-executable-jar-format.adoc#executable-jar, different approach>> and lets you actually nest jars directly.
****

To create an executable jar, we need to add the `spring-boot-maven-plugin` to our `pom.xml`.
To do so, insert the following lines just below the `dependencies` section:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
----

NOTE: The `spring-boot-starter-parent` POM includes `<executions>` configuration to bind the `repackage` goal.
If you do not use the parent POM, you need to declare this configuration yourself.
See the {spring-boot-maven-plugin-docs}#getting-started[plugin documentation] for details.

Save your `pom.xml` and run `mvn package` from the command line, as follows:

[indent=0,subs="attributes"]
----
	$ mvn package

	[INFO] Scanning for projects...
	[INFO]
	[INFO] ------------------------------------------------------------------------
	[INFO] Building myproject 0.0.1-SNAPSHOT
	[INFO] ------------------------------------------------------------------------
	[INFO] .... ..
	[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ myproject ---
	[INFO] Building jar: /Users/developer/example/spring-boot-example/target/myproject-0.0.1-SNAPSHOT.jar
	[INFO]
	[INFO] --- spring-boot-maven-plugin:{spring-boot-version}:repackage (default) @ myproject ---
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD SUCCESS
	[INFO] ------------------------------------------------------------------------
----

If you look in the `target` directory, you should see `myproject-0.0.1-SNAPSHOT.jar`.
The file should be around 10 MB in size.
If you want to peek inside, you can use `jar tvf`, as follows:

[indent=0]
----
	$ jar tvf target/myproject-0.0.1-SNAPSHOT.jar
----

You should also see a much smaller file named `myproject-0.0.1-SNAPSHOT.jar.original` in the `target` directory.
This is the original jar file that Maven created before it was repackaged by Spring Boot.

To run that application, use the `java -jar` command, as follows:

[indent=0,subs="attributes"]
----
	$ java -jar target/myproject-0.0.1-SNAPSHOT.jar

	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::  (v{spring-boot-version})
	....... . . .
	....... . . . (log output here)
	....... . . .
	........ Started Example in 2.536 seconds (JVM running for 2.864)
----

As before, to exit the application, press `ctrl-c`.



[[getting-started-whats-next]]
== What to Read Next
Hopefully, this section provided some of the Spring Boot basics and got you on your way to writing your own applications.
If you are a task-oriented type of developer, you might want to jump over to https://spring.io and check out some of the https://spring.io/guides/[getting started] guides that solve specific "`How do I do that with Spring?`" problems.
We also have Spring Boot-specific "`<<howto.adoc#howto, How-to>>`" reference documentation.

Otherwise, the next logical step is to read _<<using-spring-boot.adoc#using-boot>>_.
If you are really impatient, you could also jump ahead and read about _<<spring-boot-features.adoc#boot-features, Spring Boot features>>_.
