[[getting-started]]
= 开始使用
include::attributes.adoc[]

如果你现在正在开始使用 Spring Boot，或者有关 "`Spring`" 的相关内容，建议你开始阅读本中有关的内容。
这个通常能够回答你有关一些的基本知识，包括有"`什么是（what?）`", "`如何开始（how?）`" and "`为什么（why?）`" 等有关的问题。
这个部分包括有对 Spring Boot 的介绍，以及包括有安装的指南。
我们将会和你一起构建你的第一个 Spring Boot 应用程序，然后讨论一些我们需要了解的核心概念。



[[getting-started-introducing-spring-boot]]
== Spring Boot 介绍
Spring Boot 能够帮助你创建独立运行（stand-alone），基于 Spring 可在生产环境（production-grade）中运行的应用。
在 Spring 官方的文档中对 Spring 平台和使用的一些第三方类库进行了一些说明描述，因此你可以使用这些只是能够在很短的时间内开始使用 Spring Boot。
绝大部分的 Spring Boot 应用只需要一些很少的 Spring 配置就可以运行了。

你可以使用 Spring Boot 来创建一个 Java 应用程序，这个 Java 应用程序可以使用 `java -jar` 来运行，同时也可以使用传统的 Web 部署（war deployments）。
我们同时也提供了一个命令行工具来运行 "`spring scripts`"。

我们主要的目的是：

* 针对所有的 Spring 开发提供了一个广泛的快速和开始使用经验。
* 因为开始默认需求和实际的开发有所出入，我们提供了开箱即用的能够，能够让你更快的适应你的业务。
* 针对很多项目都需要的通用要求，我们也提供了一个广泛的非功能性特性（例如，嵌入式服务，安全性，矩阵，系统健康检查和外部扩展功能）。
* 你完全可以不需要使用代码生成功能，也不需要对 XML 进行配置。



[[getting-started-system-requirements]]
== 系统要求
Spring Boot {spring-boot-version} 版本要求至少 https://www.java.com[Java 8] 及其以上版本，目前最高能够支持到 Java 15 （包含 15）的版本。
{spring-framework-docs}/[Spring 框架（Framework） {spring-framework-version}] 的版本或者以上的版本是必须的。

能够被下面的编译工具支持：

|===
| 编译工具 | 版本

| Maven
| 3.3+

| Gradle
| 6 (6.3 或者后续版本)。 5.6.x 也是能够被支持的，但是已经准备开始不被兼容了。
|===



[[getting-started-system-requirements-servlet-containers]]
=== Servlet 容器
Spring Boot 能够支持下面的嵌入 Servlet 容器版本：

|===
| 名字 | Servlet 版本

| Tomcat 9.0
| 4.0

| Jetty 9.4
| 3.1

| Undertow 2.0
| 4.0
|===

当然，你也可以将 Spring Boot 应用部署到任何能够兼容 3.1+ 容器版本的服务器上。



[[getting-started-installing-spring-boot]]
== 安装 Spring Boot
Spring Boot 可以通过使用 "`传统（classic）`" 的 Java 开发工具或者安装一个命令行工具（command line tool）。
不管通过何种方式进行安装，你都需要  https://www.java.com[Java SDK v1.8] 或者更高的版本。
在进行安装之前，你需要通过下面的命令来检查你的环境中是否已经有安装正确的 JDK 版本。

[indent=0]
----
	$ java -version
----

如果你是一个 Java 开发的初学者或者希望对 Spring Boot 有所了解，你可能希望尝试下官方提供的  <<getting-started-installing-the-cli, Spring Boot CLI>> (命令行工具 Command Line Interface) 。
否则的话，你可以尝试从 "`传统（classic）`" 的安装介绍中开始。



[[getting-started-installation-instructions-for-java]]
=== 针对 Java 开发者的安装指南
你可以与任何 Java 标准库相同的方式来使用 Spring Boot。
为了能够让你的项目使用 Spring Boot ，将 `+spring-boot-*.jar+` 文件放到你项目中正确的 classpath 中。
Spring Boot 是不需要任何特殊的工具来进行整合的，所以你可以方便的使用任何 IDE 或者 文本编辑器。
另外的，针对 Spring Boot 应用程序也没有任何特殊的地方，你可以和你以往对 Java 进行开发的流程一样对 Spring Boot 应用进行调试（debug）。

尽管，你 _可以使用_ 拷贝 Spring Boot 的 Jar 包到你的项目路径中来运行项目，我们还是非常建议你使用一些构建工具来对依赖进行管理（例如 Maven 或者 Gradle）。



[[getting-started-maven-installation]]
==== Maven 安装
Spring Boot 能够与 Apache Maven 3.3 及其以上的版本进行兼容。
如果你的计算机或者环境中还没有安装 Maven ，请参考 https://maven.apache.org 页面中的内容来对 Maven 进行安装。

TIP: 在很多操作系统中，Maven 是可以通过一个包管理工具来进行安装的。
如果你使用的是 OSX Homebrew 操作系统，尝试运行 `brew install maven` 来进行安装。
Ubuntu 的用户可以通过运行 `sudo apt-get install maven` 来进行安装
Windows 用户也可以使用 https://chocolatey.org/[Chocolatey] 来进行安装，你需要运行 `choco install maven` 命令（这个命令运行需要具有管理员权限）。

Spring Boot 的依赖使用 `org.springframework.boot` `groupId` 来声明。
通常来说，你的 Maven POM 文件需要继承 `spring-boot-starter-parent` 项目，同时还需要声明一个或者多个 <<using-spring-boot.adoc#using-boot-starter,"`Starters`">>。
Spring Boot 同时也提供了一个可选项的 <<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven 插件（plugin）>> 来被用来创建可执行的 Jars。

更多有关开始使用 Spring Boot 和 Maven 的相关文章和内容可以在页面 {spring-boot-maven-plugin-docs}#getting-started[开始使用部分] 中找到。同时有关 Maven 插件的参考页可以在这里找到。



[[getting-started-gradle-installation]]
==== Gradle 安装
Spring Boot 能够兼容 Gradle 6 （6.3 或者后续版本）。
Gradle 5.6.x 也是能够被支持的，但是这个支持将会在后续的发布中删除。
如果你的计算机中还没有安装 Gradle ，请参考页面 https://gradle.org 中的内容来安装 Gradle。

Spring Boot 的依赖使用 `org.springframework.boot` `group` 来声明。
通常来说，你的项目需要声明一个或者多个  <<using-spring-boot.adoc#using-boot-starter, "`Starters`">>。
Spring Boot 同时也提供了一个 <<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle 插件（plugin）>> ，这个插件能够对依赖声明进行简化，同时被用来创建一个可执行的 Jars。

.Gradle Wrapper
****
Gradle Wrapper 能够为你在构建一个项目的时候，提供了一个非常简单的方式来  "`获得`" Gradle。
Gradle Wrapper 是一个小的脚本和库，你可以通过这个脚本和库来启动构建进程，通常并不需要安装 Gradle。
请查看 {gradle-docs}/gradle_wrapper.html 页面来获得更多的细节。
****

更多有关开始使用 Spring Boot 和 Gradle 的相关文章和内容可以在页面 {spring-boot-gradle-plugin-docs}#getting-started[开始使用部分] 中找到。同时有关 Gradle 插件的参考页可以在这里找到。



[[getting-started-installing-the-cli]]
=== 安装 Spring Boot 命令行
Spring Boot CLI (Command Line Interface) 是一个你可以用来快速初始化 Spring 的命令行工具。
Spring Boot 的命令行工具能够让你运行 https://groovy-lang.org/[Groovy] 脚本。这个脚本有着类似 Java 的句法。

在运行和构建 Spring Boot 应用的时候，CLI 这个工具并不是必须需要安装的。哪怕你不安装 CLI，你也能够非常快速的运行 Spring Boot 应用，但是这个官方提供的小工具能够让你更快的使用 Spring Boot。



[[getting-started-manual-cli-installation]]
==== 手工安装
你可以从 Spring 的软件仓库中下载 Spring CLI 后进行安装。

可用的下载地址，请参考下面的链接：

* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.zip[spring-boot-cli-{spring-boot-version}-bin.zip]
* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.tar.gz[spring-boot-cli-{spring-boot-version}-bin.tar.gz]

Sapshot 版本下载，snapshot 版本的意思是从最新的源代码库中进行编译构建的，通常这个版本具有更多的 Bug 修复，下载地址请访问下面的链接：
https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-cli/[snapshot 构建版本]

当你完成需要的归档文件下载到你本地计算机后，请按照链接： {github-raw}/spring-boot-project/spring-boot-cli/src/main/content/INSTALL.txt[INSTALL.txt] 安装指南的内容来解压。
整体来说，Spring CLI 是一个 `spring` 脚本 (针对 Windows 使用的是`spring.bat` )。这个可以运行的脚本文件能够在你对 `.zip` 文件解压的 `bin/` 文件夹中找到。
你还可以使用另外一个办法来使用 Spring CLI：通过一个 `.jar` 的文件使用 `java -jar` 来进行运行（在运行这个 jar 的时候，你需要确定这个 Jar 文件已经放置到了你系统中的 classpath 路径中）。



[[getting-started-sdkman-cli-installation]]
==== 使用 SDKMAN! 安装
针对在变量中设置多个版本的 SDK，你可以使用 SDKMAN! (The Software Development Kit Manager) 来进行安装。
Groovy 和 Spring Boot CLI 都已经部署到 SDKMAN! 中了，在你本地计算机中配置好 SDKMAN! 环境后，你就可以使用多版本的 Groovy 和 Spring Boot CLI。
可以使用下面的命令来通过 https://sdkman.io 来安装 Spring Boot：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk install springboot
	$ spring --version
	Spring Boot v{spring-boot-version}
----

如果你正在针对 CLI 的一些特性进行开发的话，并且你希望使用你本地编译的 CLI 构建版本安装到 SDKMAN! 中的话，你可以通过运行下面的命令来进行版本的切换：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-{spring-boot-version}-bin/spring-{spring-boot-version}/
	$ sdk default springboot dev
	$ spring --version
	Spring CLI v{spring-boot-version}
----

上面的命令显示了一个被命名为 `dev` 的 `spring` 实例安装的安装命令和安装校验。同时路径（Path）还指向到了构建的位置，因此每次通过代码重构后，你都会使用最新的 `spring` 版本。

如果你需要检查安装的版本和相关的配置，请运行下面的命令：

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ sdk ls springboot

	================================================================================
	Available Springboot Versions
	================================================================================
	> + dev
	* {spring-boot-version}

	================================================================================
	+ - local version
	* - installed
	> - currently in use
	================================================================================
----



[[getting-started-homebrew-cli-installation]]
==== OSX Homebrew 安装
如果你是 Mac 的用户，并且在你的 Mac 计算机上已经安装了 https://brew.sh/[Homebrew] 应用的话，你可以通过使用下面的命令来安装 Spring Boot CLI：

[indent=0]
----
	$ brew tap pivotal/tap
	$ brew install springboot
----

Homebrew 将会把 `spring` 安装到 `/usr/local/bin` 目录下。

NOTE: 如果你在安装的过程中出现了一些异常，或者显示包没有找到，或者没有办法进行安装，那么很有可能是安装的 brew 版本过老，需要进行更新了。
你可以直接运行 `brew update` 命令先进行更新，然后再次尝试进行安装。


[[getting-started-macports-cli-installation]]
==== MacPorts 安装
如果你是 Mac 的用户，你也可以使用 https://www.macports.org/[MacPorts] 来进行安装。 你可以通过使用下面的命令来安装 Spring Boot CLI：

[indent=0]
----
	$ sudo port install spring-boot-cli
----
MacPorts 和 Homebrew 其实是类似的一个包管理工具。

Mac 算是BSD的一个变种。所以，BSD 的包管理软件 port 被移植到 Mac 上就显的理所当然了。 MacPorts 的工作方式是下载源代码后在本地编译。
MacPorts 的理念是尽量减少对系统现有库的依赖。所以，第一次用 MacPorts 的时候，需要很长时间让 MacPorts 重新 build 整个基本库。

Homebrew  这个比较新，是在Lion之后才兴起的。 工作方式和 MacPorts类似，也是下载源代码后并在本地编译安装。

Homebrew 与 MacPorts 有两个根本的区别。

* Homebrew 的理念是尽量使用系统现有的库。这样可以大大的减少编译时间。
* package都安装到 /usr/local 下面。 这两点和 MacPorts 是完全相反的。


[[getting-started-cli-command-line-completion]]
==== Command-line 自动完成
Spring Boot CLI 包含有脚本能够提供命令行的自动完成。有关自动完成的定义请参考 https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29[BASH] 和 https://en.wikipedia.org/wiki/Z_shell[zsh] 页面中的内容。
你可以下载 `spring` 命令行的 `源代码` 脚本到任何 shell 环境中，并且添加到你自己或者系统全局的 bash 自动完成初始化。
在 Debian 操作系统中，基于操作系统的全局脚本位于 `/shell-completion/bash` 目录中。所有位于这个目录中的脚本将会在新的 shell 启动后被执行。
例如，如果你希望通过使用 SDKMAN! 来手动运行一个 Spring 的脚本来进行安装，你可以尝试使用下面的命令：

[indent=0]
----
	$ . ~/.sdkman/candidates/springboot/current/shell-completion/bash/spring
	$ spring <敲一下 TAB 键>
	  grab  help  jar  run  test  version
----

NOTE: 如果你是通过使用 Homebrew 或 MacPorts 来安装 Spring Boot CLI 的话，脚本命令行的工具将会自动注册到你的 shell 中。



[[getting-started-scoop-cli-installation]]
==== Windows Scoop 安装
如果你使用的是 Windows 操作系统，你可以使用 https://scoop.sh/[Scoop] 来进行安装。 你可以通过使用下面的命令来安装 Spring Boot CLI：

[indent=0]
----
	> scoop bucket add extras
	> scoop install springboot
----

Scoop 将会把 `spring` 安装到  `~/scoop/apps/springboot/current/bin` 目录中。

NOTE: 如果你在安装的过程中出现了一些异常，或者没有看到 app 的 manifest，那么很有可能是因为你安装的 scoop 版本过老而需要更新了。
你可以直接运行 `scoop update` 命令先进行更新，然后再次尝试进行安装。

Scoop 可以简单理解为一个在 Windows 中可以使用的包管理工具，这个包管理工具需要在 PowerShell 中运行。

我们熟知的 Ubuntu上 的apt-get（在 Ubuntu16 以上可以直接用apt了），MacOS上的 homebrew 都是很优秀的包管理工具。如果你使用的是 CentOS 或者 REHL 的话，我们应该非常熟悉使用 yum 或者 dnf 来进行安装包。

但是在 Windows 平台下，由于 Windows 的开放性，大家都是去各种网站上下载程序，一些软件开发环境的程序也很杂乱，到处都是各种下载链接，容易中病毒还浪费时间。
所以我们有开发者想要 在 Windows 平台上开发包管理工具 —— scoop，简单理解过来就是一个可以在 Windows 平台下使用 yum 或者 dnf 的工具。



[[getting-started-cli-example]]
==== Spring CLI 快速使用示例
你可以使用下面的命令行来创建 Web 应用程序来测试你的安装是否正常。
创建一个称为 `app.groovy` 的文件，文件的内容如下：

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
	@RestController
	class ThisWillActuallyRun {

		@RequestMapping("/")
		String home() {
			"Hello World!"
		}

	}
----

然后从 Shell 中运行下面的命令：

[indent=0]
----
	$ spring run app.groovy
----

NOTE: 当第一次运行你的应用程序的时候可能需要的时间比较长，这是因为系统需要从远程下载所需要的依赖。在后续运行的时候就会更加快速了。

在任何你喜欢的浏览器的地址栏中输入下面的地址：`http://localhost:8080` ，然后应该能够在浏览器中看到下面的输出：

[indent=0]
----
	Hello World!
----



[[getting-started-upgrading-from-an-earlier-version]]
=== 从早期的 Spring Boot 版本进行升级
如果你打算从 Spring Boot 的 `1.x` 版本进行升级的话，请查看  {github-wiki}/Spring-Boot-2.0-Migration-Guide["项目 WIKI 页面中`合并指南`" ] 的内容来了解有关升级的详细指南。
请查看 {github-wiki}["`发布日志（release notes）`"] 页面中的内容来了解针对每一个发行版本的 "`新的和值得注意的特性`" 的信息。

当升级到一个新的特性发布版本的时候，一些属性可能需要被重命名或者被删除。
Spring Boot 提供了一个能够分析你的应用程序的工具，你可以通过这个工具来打印出应用的环境和启动诊断工具，来确定 Spring Boot 的属性配置正确和为你提供调试信息。
如果你希望启用上面的这个特性的话，请将下面的依赖添加到你的项目中：

[source,xml,indent=0]
----
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-properties-migrator</artifactId>
		<scope>runtime</scope>
	</dependency>
----

WARNING: 添加到环境中的属性，例如当使用 `@PropertySource` 的时候，将会在诊断工具中显示出来。

NOTE: 一旦你完成了合并，请确定将上面的依赖从你的项目中删除。

如果你希望对已经安装的 CLI 工具进行升级的话，请使用正确的升级工具或者命令（例如，可以使用 `brew upgrade`）。
如果你是通过手动方式安装 CLI 的话，请参考 <<getting-started-manual-cli-installation, 标准的安装>>，请注意，当你更新你的 `PATH` 环境变量来删除任何可能存在的老的参考和应用。



[[getting-started-first-application]]
== 部署你的第一个 Spring Boot 应用
这部分的内容将会对如何开发一个小的 "`Hello World!`" web 应用程序进行指导，同时还会对使用的 Spring Boot 的关键特性进行一些提示。
我们将使用 Maven 来构建这个项目。我们选择使用 Maven 的原因是大部分的 IDE 都能很好的进行支持。

[TIP]
====
https://spring.io[spring.io] 的网站提供了很多使用 Spring Boot 的 "`开始使用（Getting Started）`" 相关的 https://spring.io/guides[指南]。
如果你需要解决一些特定的问题，请参考官方网站提供的开始使用指南。

你可以简化创建这个小应用的过程。这是因为 https://start.spring.io 网站提供了快速构建项目的指南和链接。访问 https://start.spring.io 地址，然后从依赖搜索中选择 "Web" starter。
通过上面的链接， Spring 的官方网站将会为你快速创建一个新的项目结构，随后你可以通过这个新的项目结构了 <<getting-started-first-application-code,快速进行代码开发>> 了。
有关快速开启项目的文档，请参考 {spring-initializr-docs}/#user-guide[Spring 初始化文档（Spring Initializr documentation）] 页面中内容，来获得更多的详细信息。
====

在我们开始构建示例应用之前，请打开你的命令行终端并且运行下面的命令以确定你的计算机环境中已经安装了需要的环境。
我们需要 Java 和 Maven 环境。

[indent=0]
----
	$ java -version
	java version "1.8.0_102"
	Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
	Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
----

[indent=0]
----
	$ mvn -v
	Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
	Maven home: /usr/local/Cellar/maven/3.3.9/libexec
	Java version: 1.8.0_102, vendor: Oracle Corporation
----

NOTE: 请注意，这个示例应用程序需要创建自己的目录。后面的示例内容，我们假定你已经创建了合适的目录，并且你已经在当前的目录中了。

要创建合适目录的原因是 Maven 对目录结构是有特定的约束的。



[[getting-started-first-application-pom]]
=== 创建 POM
我们需要从创建一个 Maven `pom.xml` 文件开始整个过程。
与我们做饭一样，Maven `pom.xml` 文件就好像一个菜单，我们需要使用这个来构建你的项目。
打开你常用的文本编辑器，然后将下面的内容拷贝到 pom.xml 文件中。

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
		<modelVersion>4.0.0</modelVersion>

		<groupId>com.example</groupId>
		<artifactId>myproject</artifactId>
		<version>0.0.1-SNAPSHOT</version>

		<parent>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-parent</artifactId>
			<version>{spring-boot-version}</version>
		</parent>

		<description/>
		<developers>
			<developer/>
		</developers>
		<licenses>
			<license/>
		</licenses>
		<scm>
			<url/>
		</scm>
		<url/>

		<!-- Additional lines to be added here... -->

ifeval::["{spring-boot-artifactory-repo}" != "release"]
		<!-- (you don't need this if you are using a .RELEASE version) -->
		<repositories>
			<repository>
				<id>spring-snapshots</id>
				<url>https://repo.spring.io/snapshot</url>
				<snapshots><enabled>true</enabled></snapshots>
			</repository>
			<repository>
				<id>spring-milestones</id>
				<url>https://repo.spring.io/milestone</url>
			</repository>
		</repositories>
		<pluginRepositories>
			<pluginRepository>
				<id>spring-snapshots</id>
				<url>https://repo.spring.io/snapshot</url>
			</pluginRepository>
			<pluginRepository>
				<id>spring-milestones</id>
				<url>https://repo.spring.io/milestone</url>
			</pluginRepository>
		</pluginRepositories>
endif::[]
	</project>
----

上面的 `pom.xml` 文件应该能够给你一个可以成功构建的项目。
你可以通过运行 `mvn package` 来进行测试（在当前，你可能会收到 "`jar will be empty - no content was marked for inclusion!`" 警告信息，直接忽略即可）。

NOTE: 现在，你就可以将这个 Maven 构建文件导入到任何你喜欢的 IDE 中了（绝大多数 Java IDE 现在都能够支持导入 Maven 项目）。
为了简化操作，在这个示例中，我们将不使用 IDE 而继续使用纯文本编辑器（text editor）。



[[getting-started-first-application-dependencies]]
=== 添加 Classpath 依赖
Spring Boot 提供了一系列的  "`Starters`" 来让你将 Jar 添加到你的 classpath 路径中。
我们的项目提供了一系列的 smoke tests，需要使用 `spring-boot-starter-parent` 定义在 POM 文件的 `parent` 部分。如果你对 smoke tests 不太了解的话，请参考相关定义和搜索相关文档。
在这里 smoke tests 的定义就是能够让项目能够跑起来，并且实现一些基本的功能。

`spring-boot-starter-parent` 是一个特殊的 starter。在这个定义中，我们为 Maven 提供了一些有用的默认配置。
同时 `spring-boot-starter-parent` 还提供了一些  <<using-spring-boot.adoc#using-boot-dependency-management,`dependency-management`>>。
因为上面的的配置，针对依赖，你可以针对 "`blessed`" 忽略掉 `version` 标签。

当你针对 Spring Boot 在应用中，想使用一些特定的功能或者构建一些特定的应用，你可以针对需要来选择其他的 "`Starters`"。
针对当前的示例，我们打算是构建一个 Web 应用程序，因此我们需要添加一个 `spring-boot-starter-web` 到依赖（dependency）中。
在进行上面的操作之前，我们可以通过运行下面的命令来查看我们当前项目中使用的依赖：

[indent=0]
----
	$ mvn dependency:tree

	[INFO] com.example:myproject:jar:0.0.1-SNAPSHOT
----

`mvn dependency:tree` 命令行将会针对你的项目使用的依赖打印出依赖的树结构。
现在，你可以看到 `spring-boot-starter-parent`，但是还没有添加其他的依赖。
如果想添加一些必要的依赖，编辑你的 `pom.xml` 然后添加 `spring-boot-starter-web` 依赖代码到 pom.xml 文件的 `parent` 部分后面。
具体的代码内容，请参考下面的示例：

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>
----

当你再次运行 `mvn dependency:tree` 的时候，你可以看到在你当前的项目中已经添加上去一些其他的依赖了。包括有 Tomcat web server 和 Spring Boot 本身。



[[getting-started-first-application-code]]
=== 书写代码
为了完成我们的第一个 Spring Boot 示例程序，我们需要向已经创建的项目框架中创建一个 Java 文件。
在默认情况下，Maven 会编译 `src/main/java` 目录中的源代码（这个是与 Maven 使用的约定有关的，这个目录结构可以修改，但是不建议修改，因为绝大部分人都会遵守这个约定）。
根据 Maven 的源代码约定，你需要按照下面的目录路径和文件名创建一个 Example.java 文件，完整的路径如下： `src/main/java/Example.java`。
Example.java 文件的内容，你可以直接拷贝下面的源代码。

[source,java,indent=0]
----
	import org.springframework.boot.*;
	import org.springframework.boot.autoconfigure.*;
	import org.springframework.web.bind.annotation.*;

	@RestController
	@EnableAutoConfiguration
	public class Example {

		@RequestMapping("/")
		String home() {
			return "Hello World!";
		}

		public static void main(String[] args) {
			SpringApplication.run(Example.class, args);
		}

	}
----

尽管上面代码看起来没有什么内容，但是实际上 Spring Boot 的框架已经为你做了很多工作了，在后续的章节中我们将会对代码中的一些重要内容进行解释和说明。



[[getting-started-first-application-annotations]]
==== @RestController 和 @RequestMapping 注解
在示例源代码类中的第一个注解（annotation）是 `@RestController`。
这个注解被称为 _stereotype_ 注解。在使用 Spring 的时候，需要对注解有所了解。Spring 有多个类型的注解，例如在包 org.springframework.context.annotation 和 org.springframework.stereotype 的注解。
不仅仅是 @Component，他的派生注解 @Service、@Controller、@RestController 和 @Repository都在这个包中，实际上它就是在告诉使用者这些注解提供 stereotype 的特性（或者称为功能、作用）。
Stereotype 特性最早出现在J2EE6 中，可以理解为围绕着 “元数据” 功能而发展出来的一种设计模式。
这个注解提示人们在阅读代码的时候了解 Spring 实现的功能和扮演的特定的角色。
在这个类中，我们告诉 Spring 是一个 Web 的 `@Controller`，因此 Spring 会通过这个注解来考虑这个类用于处理访问的 Web 请求。

`@RequestMapping` 注解，为我们的应用提供了 "`routing`" 信息。在这里的 routing 可以理解为路径，在我们访问 Web 资源的时候都会要求提供一个路径的信息。
具体有关这个注解的解释为任何 HTTP 的请求，如果使用了 `/` 路径的话，所有的请求将会映像到 `home` 方法，或者可以理解为 `home` 方法 将会被执行。
`@RestController` 注解将会告诉 Spring 将返回的结果使用 String 字符串来进行渲染，然后将渲染的结果返回给调用者。

@Controller 和 @RestController 之间有什么区别？ 非常简单来说  `@RestController` 是一个特殊版本的 controller。是由 `@Controller` 和 `@ResponseBody` 2 个注解合并而成的。
在没有 `@RestController` 注解之前，你可以使用 `@Controller`，同时你还需要使用 `@ResponseBody` 注解来确定返回的内容是什么。设计 `@RestController` 的目的主要也是为了针对目前越来越流行的微服务和 Rest API 的开发来设计的。

TIP: `@RestController` 和 `@RequestMapping` 注解都是 Spring MVC 中的注解（这 2 个注解是没有在 Spring Boot 中指定的）。
请参考 Spring 参考文档中的 {spring-framework-docs}/web.html#mvc[MVC 部分] 来获得更多的有关信息。



[[getting-started-first-application-auto-configuration]]
==== @EnableAutoConfiguration 注解
在示例代码中的第二个注解是 `@EnableAutoConfiguration`。
这个注解告诉 Spring Boot 如何去 "`猜测（guess）`" 你是如何希望配置 Spring 的。这个所谓的猜测过程其实也不是真的猜，是根据你添加的依赖来确定的。
当添加 `spring-boot-starter-web` 依赖后，Spring 将会添加 Tomcat 和 Spring MVC 依赖。这个自动配置假定你将会部署一个 web 应用和设置 Spring 框架。

.Starters 和 Auto-configuration
****
自动配置（Auto-configuration）被用来与 Spring 的 "`Starters`" 很好的协同工作。但是如果你还有其他的一些选项的话，你 Spring 的自动配置也会尝试去进行配置。 but the two concepts are not directly tied.
你当然也可以选择 starters 之外的依赖。 Spring Boot 仍然将会尝试对你的应用进行自动配置。
****



[[getting-started-first-application-main-method]]
==== The "`main`" Method
The final part of our application is the `main` method.
This is a standard method that follows the Java convention for an application entry point.
Our main method delegates to Spring Boot's `SpringApplication` class by calling `run`.
`SpringApplication` bootstraps our application, starting Spring, which, in turn, starts the auto-configured Tomcat web server.
We need to pass `Example.class` as an argument to the `run` method to tell `SpringApplication` which is the primary Spring component.
The `args` array is also passed through to expose any command-line arguments.



[[getting-started-first-application-run]]
=== Running the Example
At this point, your application should work.
Since you used the `spring-boot-starter-parent` POM, you have a useful `run` goal that you can use to start the application.
Type `mvn spring-boot:run` from the root project directory to start the application.
You should see output similar to the following:

[indent=0,subs="attributes"]
----
	$ mvn spring-boot:run

	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::  (v{spring-boot-version})
	....... . . .
	....... . . . (log output here)
	....... . . .
	........ Started Example in 2.222 seconds (JVM running for 6.514)
----

If you open a web browser to `http://localhost:8080`, you should see the following output:

[indent=0]
----
	Hello World!
----

To gracefully exit the application, press `ctrl-c`.



[[getting-started-first-application-executable-jar]]
=== Creating an Executable Jar
We finish our example by creating a completely self-contained executable jar file that we could run in production.
Executable jars (sometimes called "`fat jars`") are archives containing your compiled classes along with all of the jar dependencies that your code needs to run.

.Executable jars and Java
****
Java does not provide a standard way to load nested jar files (jar files that are themselves contained within a jar).
This can be problematic if you are looking to distribute a self-contained application.

To solve this problem, many developers use "`uber`" jars.
An uber jar packages all the classes from all the application's dependencies into a single archive.
The problem with this approach is that it becomes hard to see which libraries are in your application.
It can also be problematic if the same filename is used (but with different content) in multiple jars.

Spring Boot takes a <<appendix-executable-jar-format.adoc#executable-jar, different approach>> and lets you actually nest jars directly.
****

To create an executable jar, we need to add the `spring-boot-maven-plugin` to our `pom.xml`.
To do so, insert the following lines just below the `dependencies` section:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
----

NOTE: The `spring-boot-starter-parent` POM includes `<executions>` configuration to bind the `repackage` goal.
If you do not use the parent POM, you need to declare this configuration yourself.
See the {spring-boot-maven-plugin-docs}#getting-started[plugin documentation] for details.

Save your `pom.xml` and run `mvn package` from the command line, as follows:

[indent=0,subs="attributes"]
----
	$ mvn package

	[INFO] Scanning for projects...
	[INFO]
	[INFO] ------------------------------------------------------------------------
	[INFO] Building myproject 0.0.1-SNAPSHOT
	[INFO] ------------------------------------------------------------------------
	[INFO] .... ..
	[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ myproject ---
	[INFO] Building jar: /Users/developer/example/spring-boot-example/target/myproject-0.0.1-SNAPSHOT.jar
	[INFO]
	[INFO] --- spring-boot-maven-plugin:{spring-boot-version}:repackage (default) @ myproject ---
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD SUCCESS
	[INFO] ------------------------------------------------------------------------
----

If you look in the `target` directory, you should see `myproject-0.0.1-SNAPSHOT.jar`.
The file should be around 10 MB in size.
If you want to peek inside, you can use `jar tvf`, as follows:

[indent=0]
----
	$ jar tvf target/myproject-0.0.1-SNAPSHOT.jar
----

You should also see a much smaller file named `myproject-0.0.1-SNAPSHOT.jar.original` in the `target` directory.
This is the original jar file that Maven created before it was repackaged by Spring Boot.

To run that application, use the `java -jar` command, as follows:

[indent=0,subs="attributes"]
----
	$ java -jar target/myproject-0.0.1-SNAPSHOT.jar

	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::  (v{spring-boot-version})
	....... . . .
	....... . . . (log output here)
	....... . . .
	........ Started Example in 2.536 seconds (JVM running for 2.864)
----

As before, to exit the application, press `ctrl-c`.



[[getting-started-whats-next]]
== What to Read Next
Hopefully, this section provided some of the Spring Boot basics and got you on your way to writing your own applications.
If you are a task-oriented type of developer, you might want to jump over to https://spring.io and check out some of the https://spring.io/guides/[getting started] guides that solve specific "`How do I do that with Spring?`" problems.
We also have Spring Boot-specific "`<<howto.adoc#howto, How-to>>`" reference documentation.

Otherwise, the next logical step is to read _<<using-spring-boot.adoc#using-boot>>_.
If you are really impatient, you could also jump ahead and read about _<<spring-boot-features.adoc#boot-features, Spring Boot features>>_.
